steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
    - 'build'
    - '.'
    - '-t'
    - 'gcr.io/$PROJECT_ID/api-tests:latest'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/api-tests:latest'