#comment to test trigger

#this is the main idea of this yaml file for the trigger
  steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
    - 'build'
    - '.'
    - '-t'
    - 'gcr.io/$PROJECT_ID/api-tests:latest'